#ifndef X86_EXTREME_COMPOSITOR_INTERPOSE_H
#define X86_EXTREME_COMPOSITOR_INTERPOSE_H

#define X86_ENV_EXTREME         "X86_EXTREME"
#define X86_ENV_EXTREME_INSTALL "X86_EXTREME_INSTALL"
#define X86_ENV_AVX_MODE        "X86_INTERPOSE_AVX"
#define X86_ENV_LUT_MODE        "X86_INTERPOSE_LUT"

#define X86_EXTREME_INTERPOSE_VERSION "0.1.0-track-I"

#endif
